config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  get 'home/index', to: 'home#index'
  get 'client_logo', to: 'home#client_logo'

  get 'error/js'

  get 'pick_up', to: 'pick_up#index'
  put 'pick_up', to: 'pick_up#update'
  post 'pick_up', to: 'pick_up#update'
  get 'pick_up/teacher', to: 'pick_up#teacher', as: 'pick_up_teacher'
  post 'pick_up/attendance', to: 'pick_up#attendance'

  scope '/school' do
    get 'register', to: 'school#register', as: 'new_school'
    post 'register', to: 'school#save'
    get 'check_code/:code', to: 'school#check_code'
    get 'link', to: 'school#link', as: 'link_school'
  end

  get '/locations', to: 'locations#index'

  scope '/portal' do
    get 'parent', to: 'portal_guardian#index', as: 'portal_guardian_index'
    scope 'parent' do
      get 'students', to: 'portal_guardian#students', as: 'portal_guardian_students'
      get 'students/new', to: 'portal_guardian#students_new', as: 'portal_guardian_students_new'
      post 'students/new', to: 'portal_guardian#students_create'
      put 'students/:id', to: 'portal_guardian#students_update'
      get 'vehicles', to: 'portal_guardian#vehicles', as: 'portal_guardian_vehicles'
      get 'vehicles/new', to: 'portal_guardian#vehicles_new', as: 'portal_guardian_vehicles_new'
      post 'vehicles/new', to: 'portal_guardian#vehicles_create'
      put 'vehicles/:id', to: 'portal_guardian#vehicles_update'
      delete 'vehicles/:id', to: 'portal_guardian#vehicles_delete'
    end

    get 'teacher', to: 'portal_teacher#index', as: 'portal_teacher_index'
    scope 'teacher' do
      get 'status', to: 'portal_teacher#status', as: 'portal_teacher_status'
      get 'students', to: 'portal_teacher#students', as: 'portal_teacher_students'
      get 'students/new', to: 'portal_teacher#students_new', as: 'portal_teacher_students_new'
      post 'students/new', to: 'portal_teacher#students_create'

      put 'reset', to: 'portal_teacher#reset'
      put 'update/:student_id', to: 'portal_teacher#update' # This for legacy version of API
      put 'students/:student_id', to: 'portal_teacher#update', as: 'portal_teacher_update'
    end

    get 'faculty', to: 'admin#index', as: 'admin'
    scope 'faculty' do
      # resources :admins
      # resources :extra_activities
      resources :vehicles
      # resources :users
      resources :guardians
      get 'users', to: 'admin#users', as: 'admin_users'
      resources :students do
      	collection do
					post :bind, as: 'bind'
      		put :confirm, as: 'confirm'
					put :unbind, as: 'unbind'
      	end
      end
      resources :locations
      # resources :histories
      put '/change_role/:add', to: 'admin#change_role'
      delete 'teacher/:id', to: 'teachers#destroy', as: 'remove_teacher'
    end
  end

  delete '/admin/user/:uid', to: 'admin#user_delete', as: 'user_delete'
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :student_users
  has_many :users, through: :student_users

  has_many :student_activities
  has_many :activities, through: :student_activities
  
  has_many :histories

  has_many :teaching_users, -> { where(student_users: {teach: true}) }, through: :student_users, source: :user
  has_many :guarding_users, -> { where(student_users: {guard: true}) }, through: :student_users, source: :user
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    redirect_to root_path and return unless current_user.roles.include? Role.find(3)
    unconfirmed = []
    StudentUser.where('NOT confirmed and teach').each do |su|
      student = {}
      student[:id] = su.student.id
      student[:name] = su.student.name
      student[:status] = su.student.status
      student[:teach] = su.user
      unconfirmed << student
    end

    @unconfirmed_teach = unconfirmed

    students = []
    StudentUser.where('confirmed and teach').each do |su|
      student = {}
      student[:id] = su.student.id
      student[:name] = su.student.name
      student[:status] = su.student.status
      student[:teach] = su.user
      students << student
    end
    @students_teach = students

    unconfirmed = []
    StudentUser.where('NOT confirmed and guard').each do |su|
      student = {}
      student[:id] = su.student.id
      student[:name] = su.student.name
      student[:status] = su.student.status
      student[:guard] = su.user
      unconfirmed << student
    end

    @unconfirmed = unconfirmed

		students = []
    StudentUser.where('confirmed and guard').each do |su|
      student = {}
      student[:id] = su.student.id
      student[:name] = su.student.name
      student[:status] = su.student.status
      student[:guard] = su.user
      students << student
    end
    @students = students

		@all_students = Student.all.map{|s| [s.name, s.id]}
		@all_users = User.all.map{|u| [u.name, u.id]}

		respond_to do |format|
			format.html { render 'index' }
			format.json { render json: {allowed: students, unconfirmed: unconfirmed} }
		end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

	def bind
		su = StudentUser.new(student_id: params[:student_id], user_id: params[:user_id], guard: true)
		redirect_to students_path and return if su.save!
		render plain: 'ERROR: unknown error occurred' and return
	end

  def confirm
    user = User.find_by(id: params[:uid])
    render plain: 'ERROR: User not found' and return if user.nil?
    if params[:role] == 'guard'
      students = user.student_users.select{|s| s.student_id == params[:sid].to_i and s.guard == true}
    elsif params[:role] == 'teach'
      students = user.student_users.select{|s| s.student_id == params[:sid].to_i and s.teach == true}
    else
      render plain: "ERROR: unknown role #{params[:role]}" and return
    end
    render plain: 'ERROR: Student not found' and return if students.nil? or students.empty?
    render plain: 'ERROR: database corrupted' and return if students.count > 1
    student = students.first
    render plain: "ERROR: unknown error occurred with #{students}" and return if student.nil?
    render plain: 'OK' and return if student.update(confirmed: true)
    render plain: 'ERROR: unknown error occurred' and return
  end

	def unbind
    if params[:role] == 'guard'
			su = StudentUser.where(user_id: params[:uid], student_id: params[:sid], guard: true)
    elsif params[:role] == 'teach'
			su = StudentUser.where(user_id: params[:uid], student_id: params[:sid], teach: true)
    else
      render plain: "ERROR: unknown role #{params[:role]}" and return
    end
    render plain: "ERROR: User (#{params[:uid]}) or student (#{params[:sid]})not found (in that capacity - #{params[:role]})" and return if su.nil?
    render plain: 'OK' and return if su.first.delete
    render plain: 'ERROR: unknown error occurred' and return
		render json: {unbind: params[:uid], from: params[:sid]} and return
	end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :status)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
	<div class="field">
		<% @student.guarding_users.each do |guard|  %>
		<%= check_box_tag guard.id.to_s.to_sym, guard.id, true %>
		<%= f.label guard.id.to_s.to_sym, guard.name %><br>
		<% end %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Parents</h1>
<%= link_to 'New Student', new_student_path %>
<br>
<!--
<%= form_tag bind_students_path, class: 'form-inline' do %>
  <%= select_tag :student_id, options_for_select(@all_students), class: 'form-control' %>
  <%= select_tag :user_id, options_for_select(@all_users), class: 'form-control' %>
  <%= submit_tag 'Bind', class: 'btn btn-primary' %>
<% end %>
<br>
-->
<table class="table table-hover table-bordered table-condensed" style="text-align: center;">
  <thead>
    <tr>
      <th style="text-align: center;">Student Name</th>
      <th style="text-align: center;">Guardian Name</th>
      <th style="text-align: center;">Bind/Unbind</th>
    </tr>
  </thead>
  <tbody>
    <% if @unconfirmed.count > 0 and @students.count > 0 %>
      <tr>
        <td colspan="3"><h3>New Students</h3></td>
      </tr>
    <% end %>
    <% @unconfirmed.each do |student| %>
      <tr>
        <td style="font-size: 1.5em;"><%= student[:name] %></td>
        <td style="font-size: 1.5em;"><%= student[:guard].name %></td>
        <td><button class="btn btn-success", onClick="javascript: confirm(<%= "#{student[:id]}, #{student[:guard].id}" %>, 'guard');">Confirm</button></td>
      </tr>
    <% end %>

    <% if @students.count > 0 and @unconfirmed.count > 0 %>
      <tr>
        <td colspan="3"><h3>Current Students</h3></td>
      </tr>
    <% end %>
    <% @students.each do |student| %>
      <tr>
        <td style="font-size: 1.5em;"><%= student[:name] %></td>
        <td style="font-size: 1.5em;"><%= student[:guard].name %></td>
        <td><button class="btn btn-danger", onClick="javascript: unbind(<%= "#{student[:id]}, #{student[:guard].id}" %>, 'guard');">Unbind</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Teachers</h1>
<br>
<table class="table table-hover table-bordered table-condensed" style="text-align: center;">
  <thead>
    <tr>
      <th style="text-align: center;">Student Name</th>
      <th style="text-align: center;">Teacher Name</th>
      <th style="text-align: center;">Bind/Unbind</th>
    </tr>
  </thead>
  <tbody>
    <% if @unconfirmed_teach.count > 0 and @students_teach.count > 0 %>
      <tr>
        <td colspan="3"><h3>New Students</h3></td>
      </tr>
    <% end %>
    <% @unconfirmed_teach.each do |student| %>
      <tr>
        <td style="font-size: 1.5em;"><%= student[:name] %></td>
        <td style="font-size: 1.5em;"><%= student[:teach].name %></td>
        <td><button class="btn btn-success", onClick="javascript: confirm(<%= "#{student[:id]}, #{student[:teach].id}" %>, 'teach');">Confirm</button></td>
      </tr>
    <% end %>

    <% if @students_teach.count > 0 and @unconfirmed_teach.count > 0 %>
      <tr>
        <td colspan="3"><h3>Current Students</h3></td>
      </tr>
    <% end %>
    <% @students_teach.each do |student| %>
      <tr>
        <td style="font-size: 1.5em;"><%= student[:name] %></td>
        <td style="font-size: 1.5em;"><%= student[:teach].name %></td>
        <td><button class="btn btn-danger", onClick="javascript: unbind(<%= "#{student[:id]}, #{student[:teach].id}" %>, 'teach');">Unbind</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student.status %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>