config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  get 'home/index', to: 'home#index'
  get 'client_logo', to: 'home#client_logo'

  get 'error/js'

  get 'pick_up', to: 'pick_up#index'
  put 'pick_up', to: 'pick_up#update'
  post 'pick_up', to: 'pick_up#update'
  get 'pick_up/teacher', to: 'pick_up#teacher', as: 'pick_up_teacher'
  post 'pick_up/attendance', to: 'pick_up#attendance'

  scope '/school' do
    get 'register', to: 'school#register', as: 'new_school'
    post 'register', to: 'school#save'
    get 'check_code/:code', to: 'school#check_code'
    get 'link', to: 'school#link', as: 'link_school'
  end

  get '/locations', to: 'locations#index'

  scope '/portal' do
    get 'parent', to: 'portal_guardian#index', as: 'portal_guardian_index'
    scope 'parent' do
      get 'students', to: 'portal_guardian#students', as: 'portal_guardian_students'
      get 'students/new', to: 'portal_guardian#students_new', as: 'portal_guardian_students_new'
      post 'students/new', to: 'portal_guardian#students_create'
      put 'students/:id', to: 'portal_guardian#students_update'
      get 'vehicles', to: 'portal_guardian#vehicles', as: 'portal_guardian_vehicles'
      get 'vehicles/new', to: 'portal_guardian#vehicles_new', as: 'portal_guardian_vehicles_new'
      post 'vehicles/new', to: 'portal_guardian#vehicles_create'
      put 'vehicles/:id', to: 'portal_guardian#vehicles_update'
      delete 'vehicles/:id', to: 'portal_guardian#vehicles_delete'
    end

    get 'teacher', to: 'portal_teacher#index', as: 'portal_teacher_index'
    scope 'teacher' do
      get 'status', to: 'portal_teacher#status', as: 'portal_teacher_status'
      get 'students', to: 'portal_teacher#students', as: 'portal_teacher_students'
      get 'students/new', to: 'portal_teacher#students_new', as: 'portal_teacher_students_new'
      post 'students/new', to: 'portal_teacher#students_create'

      put 'reset', to: 'portal_teacher#reset'
      put 'update/:student_id', to: 'portal_teacher#update' # This for legacy version of API
      put 'students/:student_id', to: 'portal_teacher#update', as: 'portal_teacher_update'
    end

    get 'faculty', to: 'admin#index', as: 'admin'
    scope 'faculty' do
      # resources :admins
      # resources :extra_activities
      resources :vehicles
      # resources :users
      resources :guardians
      get 'users', to: 'admin#users', as: 'admin_users'
      resources :students do
      	collection do
					post :bind, as: 'bind'
      		put :confirm, as: 'confirm'
					put :unbind, as: 'unbind'
      	end
      end
      resources :locations
      # resources :histories
      put '/change_role/:add', to: 'admin#change_role'
      delete 'teacher/:id', to: 'teachers#destroy', as: 'remove_teacher'
    end
  end

  delete '/admin/user/:uid', to: 'admin#user_delete', as: 'user_delete'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :student_activities
  has_many :students, through: :student_activities
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
  belongs_to :location
  belongs_to :vehicle
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates :name, uniqueness: true
end

app/models/portal.rb
class Portal < ActiveRecord::Base
	has_many :roles
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :user_roles
	has_many :users, through: :user_roles
	has_many :portals
end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, uniqueness: true
  validates :email, uniqueness: true
  validates :code, uniqueness: true
  
  has_many :school_users
  has_many :users, through: :school_users
end

app/models/school_user.rb
class SchoolUser < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: :school_id}

  belongs_to :school
  belongs_to :user
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :student_users
  has_many :users, through: :student_users

  has_many :student_activities
  has_many :activities, through: :student_activities
  
  has_many :histories

  has_many :teaching_users, -> { where(student_users: {teach: true}) }, through: :student_users, source: :user
  has_many :guarding_users, -> { where(student_users: {guard: true}) }, through: :student_users, source: :user
end

app/models/student_user.rb
class StudentUser < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: [:student_id, :guard]}
  validates :user_id, uniqueness: {scope: [:student_id, :teach]}

  belongs_to :student
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :token_authenticatable
  has_many :authentication_tokens

  validates :email, uniqueness: true
  # validates :reset_password_token, uniqueness: true

  has_many :user_roles
  has_many :roles, through: :user_roles

  has_many :vehicle_users
  has_many :vehicles, through: :vehicle_users

	has_many :school_users
	has_many :schools, through: :school_users

  has_many :student_users
  has_many :students, through: :student_users
  
  has_many :histories

  has_many :teaching_students, -> { where(student_users: {teach: true}) }, through: :student_users, source: :student

  has_many :unconfirmed_students, -> { where(student_users: {guard: true, confirmed: false}) }, through: :student_users, source: :student
  has_many :confirmed_students, -> { where(student_users: {guard: true, confirmed: true}) }, through: :student_users, source: :student

  has_many :default_teaching_students, -> { where(student_users: {default_teach: true}) }, through: :student_users, source: :student
  has_many :default_guarding_students, -> { where(student_users: {default_guard: true, confirmed: true}) }, through: :student_users, source: :student
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  validates :plate, uniqueness: true
  
  has_many :vehicle_users
  has_many :users, through: :vehicle_users
end

app/models/vehicle_user.rb
class VehicleUser < ActiveRecord::Base
  validates :user_id, uniqueness: {scope: :vehicle_id}

  belongs_to :vehicle
  belongs_to :user
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pick_up_helper.rb
module PickUpHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/admin/index.html.erb
<h1>Admin Portal</h1>
<h2>Users</h2>
<table border="0">
  <tr>
    <th>Name</th>
    <th>Email</th>
		<% Role.all.each do |r| %>
			<th><%= r.role %></th>
		<% end %>
    <th>Actions</th>
  </tr>
  <% @users.each do |u| %>
    <tr>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
			<% Role.all.each do |r| %>
				<% if u.id == current_user.id %>
					<td><%= check_box_tag u.id, r.id, (u.roles.include? r), disabled: true, onchange: 'modRole(this);' %></td>
				<% else %>
					<td><%= check_box_tag u.id, r.id, (u.roles.include? r), onchange: 'modRole(this);' %></td>
				<% end %>
			<% end %>
      <td><%= link_to 'Delete', user_delete_path(u.id), method: :delete, confirm: "Are you sure you want to remove #{u.name}?" %></td>
    </tr>
  <% end %>
</table><br>

<h2>Students | <%= link_to 'New', new_student_path %></h2>
<table border="0">
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  <% @students.each do |s| %>
    <tr>
      <td><%= s.name %></td>
      <td><%= link_to 'Delete', student_path(s.id), method: :delete, confirm: "Are you sure you want to remove #{s.name}?" %></td>
    </tr>
  <% end %>
</table><br>

app/views/admin/users.html.erb
<table class="table table-hover table-bordered">
	<thead>
		<th>Name</th>
		<th>Parent</th>
		<th>Teacher</th>
		<th>Admin</th>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<% roles = user.roles.collect{|r| r.role} %>
			<tr class="<%= 'active' %>">
				<td><span style="font-size: 1.5em;"><%= user.name %></span></td>
				<% %w(Parent Teacher Faculty).each do |role| %>
				<td>
					<input type="checkbox" autocomplete="off" <%= 'checked' if roles.include? role %> id="<%= user.id %>" value="<%= role %>" onChange="modRole(this);">
				</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>