config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  get 'home/index', to: 'home#index'
  get 'client_logo', to: 'home#client_logo'

  get 'error/js'

  get 'pick_up', to: 'pick_up#index'
  put 'pick_up', to: 'pick_up#update'
  post 'pick_up', to: 'pick_up#update'
  get 'pick_up/teacher', to: 'pick_up#teacher', as: 'pick_up_teacher'
  post 'pick_up/attendance', to: 'pick_up#attendance'

  scope '/school' do
    get 'register', to: 'school#register', as: 'new_school'
    post 'register', to: 'school#save'
    get 'check_code/:code', to: 'school#check_code'
    get 'link', to: 'school#link', as: 'link_school'
  end

  get '/locations', to: 'locations#index'

  scope '/portal' do
    get 'parent', to: 'portal_guardian#index', as: 'portal_guardian_index'
    scope 'parent' do
      get 'students', to: 'portal_guardian#students', as: 'portal_guardian_students'
      get 'students/new', to: 'portal_guardian#students_new', as: 'portal_guardian_students_new'
      post 'students/new', to: 'portal_guardian#students_create'
      put 'students/:id', to: 'portal_guardian#students_update'
      get 'vehicles', to: 'portal_guardian#vehicles', as: 'portal_guardian_vehicles'
      get 'vehicles/new', to: 'portal_guardian#vehicles_new', as: 'portal_guardian_vehicles_new'
      post 'vehicles/new', to: 'portal_guardian#vehicles_create'
      put 'vehicles/:id', to: 'portal_guardian#vehicles_update'
      delete 'vehicles/:id', to: 'portal_guardian#vehicles_delete'
    end

    get 'teacher', to: 'portal_teacher#index', as: 'portal_teacher_index'
    scope 'teacher' do
      get 'status', to: 'portal_teacher#status', as: 'portal_teacher_status'
      get 'students', to: 'portal_teacher#students', as: 'portal_teacher_students'
      get 'students/new', to: 'portal_teacher#students_new', as: 'portal_teacher_students_new'
      post 'students/new', to: 'portal_teacher#students_create'

      put 'reset', to: 'portal_teacher#reset'
      put 'update/:student_id', to: 'portal_teacher#update' # This for legacy version of API
      put 'students/:student_id', to: 'portal_teacher#update', as: 'portal_teacher_update'
    end

    get 'faculty', to: 'admin#index', as: 'admin'
    scope 'faculty' do
      # resources :admins
      # resources :extra_activities
      resources :vehicles
      # resources :users
      resources :guardians
      get 'users', to: 'admin#users', as: 'admin_users'
      resources :students do
      	collection do
					post :bind, as: 'bind'
      		put :confirm, as: 'confirm'
					put :unbind, as: 'unbind'
      	end
      end
      resources :locations
      # resources :histories
      put '/change_role/:add', to: 'admin#change_role'
      delete 'teacher/:id', to: 'teachers#destroy', as: 'remove_teacher'
    end
  end

  delete '/admin/user/:uid', to: 'admin#user_delete', as: 'user_delete'
end

app/controllers/portal_teacher_controller.rb
class PortalTeacherController < ApplicationController
	before_filter :verify_role
	
	def verify_role
		redirect_to root_path unless current_user.roles.include? Role.find(2)
	end


  def index
		redirect_to "/portal/teacher/#{Role.find(2).portals.first.name}"
  end

  def students
    @students = []
    User.find_by(email: current_user.email).teaching_students.each do |s|
      student = {}
      student[:id] = s.id
      student[:name] = s.name
      student[:status] = 'Pick Up'
      student[:location] = 'None'
      history = History.where('created_at >= ?', Time.zone.now.beginning_of_day).select{|hs| hs.student_id == s.id}.last
      unless history.nil?
        student[:status] = history.status
        student[:location] = history.location.name unless history.location.nil?
      end
      @students << student # if s.status == 'En Route'
    end
    @students.sort_by!{|k| k[:name]}
    respond_to do |format|
      format.html { render 'students' }
      format.json { render json: {"students": @students} }
    end
  end

  def students_new
    @student = Student.new
  end

  def students_create
    s = Student.find_or_create_by(name: params[:student][:name])
    current_user.teaching_students << s
    StudentUser.where('student_id = ? and user_id = ?', s.id, current_user.id).first.update(confirmed: true)
    respond_to do |format|
      format.html { redirect_to portal_teacher_students_path }
      format.json { render json: {status: 'OK'} }
    end
  end

  def status
  end

  def reset
    current_user.teaching_students.each do |student|
      History.create(student_id: student.id, user_id: current_user.id, status: 'In Room')
    end
    render plain: 'OK' and return
  end

  def update
    render plain: 'ERROR: no student selected' and return if params[:student_id].nil?
    render plain: "ERROR: student #{params[:student_id]} not found!" and return if Student.find_by(id: params[:student_id]).nil?
    if params[:status].nil?
      status = 'Pick Up'
    else
      status = params[:status]
    end

		Student.find(params[:student_id]).update(status: params[:status])
    @history = History.new(student_id: params[:student_id], user_id: User.find_by(email: current_user.email).id, status: status)
    if @history.save
      respond_to do |format|
        format.html {
          render inline: "<script type=\"text/javascript\">alert('Status updated successfully'); window.history.back();</script>"
        }
        format.json {
          render json: {'status': 'OK'}
        }
      end
    else
      respond_to do |format|
        format.html {
          render js: 'alert("ERROR");' and return
        }
        format.json {
          render json: {'status': "ERROR saving ''${s}''"} and return
        }
      end
    end
  end
end

app/helpers/portal_teacher_helper.rb
module PortalTeacherHelper
end

app/views/portal_teacher/_menu.html.erb
<h1>Teacher Portal</h1>

app/views/portal_teacher/index.html.erb
<%= render 'menu' %>
Please click a button above

app/views/portal_teacher/status.html.erb
<button class="btn btn-danger" onClick="resetAll();">Reset</button>
<%= render 'menu' %>
<table border="0" id="status_view">
  <tr>
    <th>Absent</th>
    <th>Name</th>
    <th>Status</th>
    <th>Parent Name</th>
    <th>Location</th>
    <th>Action</th>
  </tr>
</table>
<script type="text/javascript">
  start_status_view();
</script>

app/views/portal_teacher/students.html.erb
<%= render 'menu' %>
<%= link_to 'New Student', '/portal/teacher/students/new' %>
<% if @students.count > 0 %>
  <h3>Students</h3>
  <table>
    <tr>
      <th>Student</th>
      <th>Status</th>
    </tr>
    <% @students.each do |s| %>
      <tr>
        <td><%= s[:name] %></td>
        <td><%= s[:status] %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/portal_teacher/students_new.html.erb
<h1>New Student</h1>

<%= form_for(@student, url: '/portal/teacher/students/new') do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', portal_guardian_students_path %>