config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'home#index'
  get 'home/index', to: 'home#index'
  get 'client_logo', to: 'home#client_logo'

  get 'error/js'

  get 'pick_up', to: 'pick_up#index'
  put 'pick_up', to: 'pick_up#update'
  post 'pick_up', to: 'pick_up#update'
  get 'pick_up/teacher', to: 'pick_up#teacher', as: 'pick_up_teacher'
  post 'pick_up/attendance', to: 'pick_up#attendance'

  scope '/school' do
    get 'register', to: 'school#register', as: 'new_school'
    post 'register', to: 'school#save'
    get 'check_code/:code', to: 'school#check_code'
    get 'link', to: 'school#link', as: 'link_school'
  end

  get '/locations', to: 'locations#index'

  scope '/portal' do
    get 'parent', to: 'portal_guardian#index', as: 'portal_guardian_index'
    scope 'parent' do
      get 'students', to: 'portal_guardian#students', as: 'portal_guardian_students'
      get 'students/new', to: 'portal_guardian#students_new', as: 'portal_guardian_students_new'
      post 'students/new', to: 'portal_guardian#students_create'
      put 'students/:id', to: 'portal_guardian#students_update'
      get 'vehicles', to: 'portal_guardian#vehicles', as: 'portal_guardian_vehicles'
      get 'vehicles/new', to: 'portal_guardian#vehicles_new', as: 'portal_guardian_vehicles_new'
      post 'vehicles/new', to: 'portal_guardian#vehicles_create'
      put 'vehicles/:id', to: 'portal_guardian#vehicles_update'
      delete 'vehicles/:id', to: 'portal_guardian#vehicles_delete'
    end

    get 'teacher', to: 'portal_teacher#index', as: 'portal_teacher_index'
    scope 'teacher' do
      get 'status', to: 'portal_teacher#status', as: 'portal_teacher_status'
      get 'students', to: 'portal_teacher#students', as: 'portal_teacher_students'
      get 'students/new', to: 'portal_teacher#students_new', as: 'portal_teacher_students_new'
      post 'students/new', to: 'portal_teacher#students_create'

      put 'reset', to: 'portal_teacher#reset'
      put 'update/:student_id', to: 'portal_teacher#update' # This for legacy version of API
      put 'students/:student_id', to: 'portal_teacher#update', as: 'portal_teacher_update'
    end

    get 'faculty', to: 'admin#index', as: 'admin'
    scope 'faculty' do
      # resources :admins
      # resources :extra_activities
      resources :vehicles
      # resources :users
      resources :guardians
      get 'users', to: 'admin#users', as: 'admin_users'
      resources :students do
      	collection do
					post :bind, as: 'bind'
      		put :confirm, as: 'confirm'
					put :unbind, as: 'unbind'
      	end
      end
      resources :locations
      # resources :histories
      put '/change_role/:add', to: 'admin#change_role'
      delete 'teacher/:id', to: 'teachers#destroy', as: 'remove_teacher'
    end
  end

  delete '/admin/user/:uid', to: 'admin#user_delete', as: 'user_delete'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  validates :plate, uniqueness: true
  
  has_many :vehicle_users
  has_many :users, through: :vehicle_users
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    redirect_to root_path unless current_user.roles.include? Role.find(3)
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicles_path, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:plate, :description)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plate %><br>
    <%= f.text_field :plate %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Plate</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.plate %></td>
        <td><%= vehicle.description %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Delete', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plate:</strong>
  <%= @vehicle.plate %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vehicle.description %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>